package com.poolborges.example.cayenne.persistence;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _Gallery was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Gallery extends CayenneDataObject {

    public static final String NAME_PROPERTY = "name";
    public static final String PAINTINGS_PROPERTY = "paintings";

    public static final String ID_PK_COLUMN = "id";

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void addToPaintings(Painting obj) {
        addToManyTarget(PAINTINGS_PROPERTY, obj, true);
    }
    public void removeFromPaintings(Painting obj) {
        removeToManyTarget(PAINTINGS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Painting> getPaintings() {
        return (List<Painting>)readProperty(PAINTINGS_PROPERTY);
    }


}
